#include "../../../../test/CuTest.h"

#include "EncodeSos.h"

#include <stdlib.h>


CuSuite* EncodeSosMailGetTestSuite(void);

void encodeSosMail_test(CuTest *tc);
void bitPackingEncodingSosMail_test(CuTest *tc);


CuSuite* EncodeSosMailGetTestSuite()
{
    CuSuite *suite = CuSuiteNew();
    SUITE_ADD_TEST(suite, encodeSosMail_test);
    SUITE_ADD_TEST(suite, bitPackingEncodingSosMail_test);
    return suite;
}

void encodeSosMail_test(CuTest *tc)
{
#define ARRAY_SIZE 6
    struct SosMail input1[ARRAY_SIZE] = {
        { 1, 58, 50, 0, 113, 1234, 0, "Nurcy",      0, 0, 0,  215733663, 0, 10, 0 }, /* (SOS - VALID) */
        { 0,  0,  0, 0,   0,    0, 0, {0},          0, 0, 0,          0, 0,  0, 0 }, /* (SOS - INVALID INPUT) */
        { 1, 62, 98, 0, 414, 9999, 0, "Neo Cortex", 0, 0, 0, 1453159363, 0,  1, 0 }, /* (SOS - VALID) */
        { 0,  0,  0, 0,   0,    0, 0, {0},          0, 0, 0,          0, 0,  0, 0 }, /* (SOS - INVALID INPUT) */
        { 1,  1,  3, 0, 100,    0, 0, "V",          0, 0, 0,  725035086, 0,  5, 0 }, /* (SOS - VALID) */
        { 0,  0,  0, 0,   0,    0, 0, {0},          0, 0, 0,          0, 0,  0, 0 }  /* (SOS - INVALID INPUT) */
    };

    char input2[ARRAY_SIZE][54 + 1] = { {0} };

    int actualReturnResults[ARRAY_SIZE];

    const int expected[ARRAY_SIZE] = { NoError, InputError, NoError, InputError, NoError, InputError };

    /*
     * To be clear: Encoding depends on random integers generated by `rand()` that are inserted in the password.
     *              Then, final passwords contain random data, and we do not check them, because the implementation
     *              of `rand()` may not be the same beetwen compilers nor platforms, and it might even be updated
     *              in the future.
     *              If we design our code carefully, and we cover the whole encoding process with tests, this can be
     *              irrelevant.
     */

    int i;
    for (i = 0; i < ARRAY_SIZE; ++i) {
        actualReturnResults[i] = encodeSosMail(&input1[i], input2[i]);
        CuAssertIntEquals(tc, expected[i], actualReturnResults[i]);
    }
#undef ARRAY_SIZE
}

void bitPackingEncodingSosMail_test(CuTest *tc)
{
#define ARRAY_SIZE 6
    const struct SosMail input1[ARRAY_SIZE] = {
        { 1, 58, 50,  1982204, 113,  1234, 29718, "Nurcy",      0, 0, 0,  215733663, 0, 10, 0 },
        { 1, 58, 50,  1982204, 113,  1234, 29718, "Nurry",      0, 0, 0,  215733663, 0, 10, 0 },
        { 1, 62, 98,  6157229, 414,  9999, 10445, "Neo Cortex", 0, 0, 0, 1453159363, 0,  1, 0 },
        { 1, 63, 98,  9456822, 414, 65535, 50672, "Neo Cortex", 0, 0, 0,  324088359, 0,  1, 0 },
        { 1,  1,  3, 10818328, 100,     0, 32793, "V",          0, 0, 0,  725035086, 0,  5, 0 },
        { 1,  1,  3, 16451154, 100,     0, 22240, "",           0, 0, 0, 1441989758, 0,  5, 0 }
    };

    char input2[ARRAY_SIZE][33] = { {0}, {0}, {0}, {0}, {0}, {0} };

    const char expected[ARRAY_SIZE][33] = {
        { 0xA1, 0x93, 0xF1, 0xFB, 0x78, 0xC4, 0x91, 0x26, 0xB0, 0xA0, 0x73, 0xAA, 0x93, 0x1B, 0xCB, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF8, 0xAC, 0xDE, 0x66, 0x00, 0x00, 0x00, 0x00, 0x50, 0x00 }, /* (SOS - VALID) */
        { 0xA1, 0x93, 0xF1, 0xFB, 0x78, 0xC4, 0x91, 0x26, 0xB0, 0xA0, 0x73, 0xAA, 0x93, 0x93, 0xCB, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF8, 0xAC, 0xDE, 0x66, 0x00, 0x00, 0x00, 0x00, 0x50, 0x00 }, /* (SOS - INVALID) */
        { 0xE1, 0x13, 0xB7, 0xCE, 0x77, 0x79, 0x7E, 0x38, 0x69, 0x46, 0x71, 0x2A, 0x7B, 0x03, 0x19, 0x7A, 0x93, 0xA3, 0x2B, 0xC3, 0x03, 0x00, 0x00, 0x18, 0x9E, 0xEB, 0xB4, 0x02, 0x00, 0x00, 0x00, 0x08, 0x00 }, /* (SOS - VALID) */
        { 0xF1, 0x13, 0xDB, 0x32, 0x41, 0x7A, 0xFE, 0xFF, 0x87, 0x2F, 0x76, 0x2A, 0x7B, 0x03, 0x19, 0x7A, 0x93, 0xA3, 0x2B, 0xC3, 0x03, 0x00, 0x00, 0x38, 0x91, 0x89, 0x9A, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00 }, /* (SOS - INVALID) */
        { 0x11, 0x18, 0x60, 0x4C, 0x94, 0x92, 0x01, 0x00, 0xC8, 0x00, 0xB4, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x70, 0x42, 0xB9, 0x59, 0x01, 0x00, 0x00, 0x00, 0x28, 0x00 }, /* (SOS - VALID) */
        { 0x11, 0x18, 0x48, 0x19, 0xEC, 0x93, 0x01, 0x00, 0x00, 0xB7, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF0, 0x23, 0x98, 0xAF, 0x02, 0x00, 0x00, 0x00, 0x28, 0x00 }, /* (SOS - INVALID) */
    };

    int i, j;
    for (i = 0; i < ARRAY_SIZE; ++i) {
        bitPackingEncodingSos(&input1[i], input2[i]);
        for (j = 0; j < 14; ++j) {
            CuAssertIntEquals(tc, expected[i][j], input2[i][j]);
        }
    }
#undef ARRAY_SIZE
}