#include "../../../../test/CuTest.h"

#include "EncodeWonderMail.h"

#include <stdlib.h>
#include <stdio.h>


CuSuite* EncodeWonderMailGetTestSuite(void);

void encodeWonderMail_test(CuTest *tc);
void bitPackingEncodingWonderMail_test(CuTest *tc);


CuSuite* EncodeWonderMailGetTestSuite()
{
    CuSuite *suite = CuSuiteNew();
    SUITE_ADD_TEST(suite, encodeWonderMail_test);
    SUITE_ADD_TEST(suite, bitPackingEncodingWonderMail_test);
    return suite;
}

void encodeWonderMail_test(CuTest *tc)
{
#define ARRAY_SIZE 10
    struct WonderMail input1[ARRAY_SIZE] = {
        { 5, 2, 0,   7,   8,   9, 5,   9,  0,   3,  18, 255,  1,  1 }, /* (WM - VALID) */
        { 5, 2, 0, 500,   8,   9, 5,   9,  0,   3,   3, 255,  1,  1 }, /* (WM - INVALID INPUT) */
        { 5, 2, 0, 197, 131, 189, 1,  20,  0, 158,  34,   1,  2,  6 }, /* (WM - VALID) */
        { 0, 0, 0,   0,   0,   0, 0,   0,  0,   0,   0,   0,  0,  0 }, /* (WM - INVALID INPUT) */
        { 5, 2, 0, 281,  25,   9, 9,   0, 37,  13, 130, 255, 62, 98 }, /* (WM - VALID) */
        { 5, 4, 0, 149, 149, 112, 0,   0,  0,   0,  54, 255,  0,  3 }, /* (WM - VALID) */
        { 5, 3, 0, 267, 267, 111, 0,   0,  0,   9, 237, 255, 36, 20 }, /* (WM - VALID) */
        { 5, 4, 5,  37,  37, 113, 3,  53,  0, 103, 254, 255, 34, 24 }, /* (WM - VALID - SPECIAL EVOLVE) */
        { 5, 4, 6, 192, 192,  89, 3, 134,  0, 169, 215, 255, 42,  7 }, /* (WM - VALID - SPECIAL FOOD) */
        { 5, 4, 6, 192, 192,  89, 3, 134,  0, 169, 215, 255, 42,  7 }  /* (WM - VALID - SPECIAL FOOD) */
    };

    char input2[ARRAY_SIZE][24 + 1] = { {0} };
    const int input3[ARRAY_SIZE] = { 0, 0, 0, 1, 1, 1, 0, 1, 1, 0 };

    int actualReturnResults[ARRAY_SIZE];

    const int expected[ARRAY_SIZE] = { NoError, MultipleError, NoError, MultipleError, NoError, NoError, NoError, NoError, NoError };

    /*
     * To be clear: Encoding depends on random integers generated by `rand()` that are inserted in the password.
     *              Then, final passwords contain random data, and we do not check them, because the implementation
     *              of `rand()` may not be the same beetwen compilers nor platforms, and it might even be updated
     *              in the future.
     *              If we design our code carefully, and we cover the whole encoding process with tests, this can be
     *              irrelevant.
     */

    int i;
    for (i = 0; i < ARRAY_SIZE; ++i) {
        fflush(stderr);
        actualReturnResults[i] = encodeWonderMail(&input1[i], input2[i], input3[i]);
        CuAssertIntEquals(tc, expected[i], actualReturnResults[i]);
    }
#undef ARRAY_SIZE
}

void bitPackingEncodingWonderMail_test(CuTest *tc)
{
#define ARRAY_SIZE 9
    const struct WonderMail input1[ARRAY_SIZE] = {
        { 5, 2, 0,   7,   8,   9, 5,   9,  0,   3,  18, 255,  1,  1 }, /* (WM - VALID) */
        { 5, 2, 0, 500,   8,   9, 5,   9,  0,   3,   3, 255,  1,  1 }, /* (WM - INVALID INPUT) */
        { 5, 2, 0, 197, 131, 189, 1,  20,  0, 158,  34,   1,  2,  6 }, /* (WM - VALID) */
        { 0, 0, 0,   0,   0,   0, 0,   0,  0,   0,   0,   0,  0,  0 }, /* (WM - INVALID INPUT) */
        { 5, 2, 0, 281,  25,   9, 9,   0, 37,  13, 130, 255, 62, 98 }, /* (WM - VALID) */
        { 5, 4, 0, 149, 149, 112, 0,   0,  0,   0,  54, 255,  0,  3 }, /* (WM - VALID) */
        { 5, 3, 0, 267, 267, 111, 0,   0,  0,   9, 237, 255, 36, 20 }, /* (WM - VALID) */
        { 5, 4, 5,  37,  37, 113, 3,  53,  0, 103, 254, 255, 34, 24 }, /* (WM - VALID - SPECIAL EVOLVE) */
        { 5, 4, 6, 192, 192,  89, 3, 134,  0, 169, 215, 255, 42,  7 }, /* (WM - VALID - SPECIAL FOOD) */
    };
    char input2[ARRAY_SIZE][14] = { {0}, {0}, {0}, {0}, {0}, {0}, {0}, {0}, {0} };

    const char expected[ARRAY_SIZE][14] = {
        { 0x25, 0x38, 0x80, 0x20, 0xA1, 0x12, 0x80, 0x01, 0x89, 0xFF, 0x40, 0x00, 0x00, 0x00 },
        { 0x25, 0xA0, 0x8F, 0x20, 0xA1, 0x12, 0x80, 0x81, 0x81, 0xFF, 0x40, 0x00, 0x00, 0x00 },
        { 0x25, 0x28, 0x36, 0xA8, 0x37, 0x28, 0x00, 0x4F, 0x91, 0x00, 0x81, 0x01, 0x00, 0x00 },
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        { 0x25, 0xC8, 0x98, 0x21, 0x21, 0x01, 0xCA, 0x06, 0xC1, 0x7F, 0x9F, 0x18, 0x00, 0x00 },
        { 0x45, 0xA8, 0x54, 0x09, 0x0E, 0x00, 0x00, 0x00, 0x9B, 0x7F, 0xC0, 0x00, 0x00, 0x00 },
        { 0x35, 0x58, 0xB8, 0xF0, 0x0D, 0x00, 0x80, 0x84, 0xF6, 0x7F, 0x12, 0x05, 0x00, 0x00 },
        { 0xC5, 0x2A, 0x51, 0x22, 0x6E, 0x6A, 0x80, 0x33, 0xFF, 0x7F, 0x11, 0x06, 0x00, 0x00 },
        { 0x45, 0x03, 0x06, 0x2C, 0x6B, 0x0C, 0x81, 0xD4, 0xEB, 0x7F, 0xD5, 0x01, 0x00, 0x00 }
    };

    int i, j;
    for (i = 0; i < ARRAY_SIZE; ++i) {
        fflush(stderr);
        bitPackingEncodingWonderMail(&input1[i], input2[i]);
        for (j = 0; j < 14; ++j) {
            CuAssertIntEquals(tc, expected[i][j], input2[i][j]);
        }        
    }
#undef ARRAY_SIZE
}